# Uncomment below to set the Huggingface token
HF_TOKEN=hf_XXX
PJRT_DEVICE=TPU
XLA_IR_DEBUG=1
XLA_HLO_DEBUG=1
PROFILE_EPOCH=0
PROFILE_STEP=3
PROFILE_DURATION_MS=120000
XLA_USE_SPMD=1
MAX_STEPS=20
SEQ_LENGTH=2048
BATCH_SIZE=64
ENABLE_PJRT_COMPATIBILITY=true
#SEQ_LENGTH=4096
#BATCH_SIZE= #512
PT_XLA_DEBUG=1
